# Generated by Django 2.2.6 on 2021-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201222_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст новой записи', max_length=2000, verbose_name='текст'),
        ),
    ]
