# Generated by Django 2.2.6 on 2021-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='введите название группы', max_length=200, verbose_name='название группы'),
        ),
    ]
