# Generated by Django 2.2.6 on 2021-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210105_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст новой записи1', max_length=2000, verbose_name='текст'),
        ),
    ]
