# Generated by Django 2.2.6 on 2021-01-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210106_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст новой записи', max_length=2000, verbose_name='текст'),
        ),
    ]
