# Generated by Django 2.2.6 on 2021-01-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_users_follow_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_follow_author',
        ),
    ]
